<!DOCTYPE html>
<html lang="en-us">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Certificates</title>
    <!--Search engine meta-->
    <meta name="Trey Jacobsen's Certificates"
          content="Trey Jacobsen has a Bachelor's degree and certifications in Python, C#, C++, C, Java, JavaScript, Swift, Ruby, Unity, and more!" />
    <!--Twitter card link meta-->
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@TreyJacobsen" />
    <meta name="twitter:title" content="Trey Jacobsen" />
    <meta name="twitter:description" content="Trey Jacobsen's Portfolio of Certificates" />
    <meta name="twitter:image" content="https://www.treyjacobsen.me/Images/DocumentSmaller.jpg" />
    <meta name="twitter:image:alt" content="Image of Trey Jacobsen" />
    <!--Facebook link meta-->
    <meta property="og:title" content="Trey Jacobsen's Portfolio" />
    <meta property="og:description" content="Trey Jacobsen's Certificate Portfolio" />
    <meta property="og:image" content="https://www.treyjacobsen.me/Images/DocumentSmaller.jpg" />
    <!--Primary StyleSheet for project-->
    <link href="Style.css" rel="stylesheet" />
    <!--website icon, my face-->
    <link rel="icon" type="image/x-icon" href="Images/SmallerMe.png" alt="Small picture of Trey Jacobsen" />
    <!--Mobile Compatibility-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--jquery script-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!--php doesn't work with HTML-->
    <?php
    $files = implode("^", scandir("Certs"));
    ?>
    <script>
        let files = "<?php echo $files; ?>";
    </script>
    <!--Primary script for website-->
    <script src="Script.js"></script>
</head>
<body>
    <!--Div containing all content-->
    <div id="all">
        <header>
            <h2><a href="Index.html" id="home" class="tabs" rel="prev"> Home </a>|<a href="Certificates.php" id="certificates" class="tabs" rel="canonical"> Certificates </a>|<a href="Projects.html" id="projects" class="tabs" rel="next"> Projects </a></h2>
        </header>
        <div id="test">
        </div>
        <p>These are my computer programming certificates. I also have an <strong>Associate's in Computer Programming</strong> and a <strong>Bachelor's in Business</strong> from MSUB.</p>
        <!--I got sorting code from W3Schools website and made a minor modification to sort column zero
            Some certificate dates may say they were recieved later than where they are located as
            I have recertified after the course was updated with new content-->
        <p><br />To sort certificates click on the headers, the Certificates column sorts by date I <i>originally</i> recieved them.</p>
        <table id="myTable">
            <thead>
                <tr>
                    <th id="cert" onclick="sortTable(0)"> Certificates ↕ </th>
                    <th id="school" onclick="sortTable(1)"> School ↕ </th>
                    <th id="class" onclick="sortTable(2)"> Class ↕ </th>
                </tr>
            </thead>
            <tbody>

                <!--Table Contents generated by Script.js!-->
            </tbody>
        </table>
        <noscript>You must have Javascript enabled to view this table!</noscript>
        <br />
        <a href="#top"><div id="toTop" hidden>^Back to Top</div></a>
        <!--My Social Media Pages, logos found through Google and not for commercial use-->
        <div id="social">
            <p>
                <a href="https://www.linkedin.com/in/treyjacobsen" target="_blank" rel="noreferrer noopener"><img class="socials" src="Images/Linkedin.png" alt="Linkedin Logo" /></a>
                <a href="https://www.github.com/lonefullmetal" target="_blank" rel="noreferrer noopener"><img class="socials" src="Images/GitHub.png" alt="GitHub Logo" /></a>
                <a href="https://www.sololearn.com/profile/1035886" target="_blank" rel="noreferrer noopener"><img class="socials" src="Images/SoloLearn.png" alt="SoloLearn Logo" /></a>
                <a href="https://www.twitter.com/TreyJacobsen" target="_blank" rel="noreferrer noopener"><img class="socials" src="Images/Twitter.png" alt="Twitter Logo" /></a>
            </p>
        </div>
        <br />
    </div>
</body>
</html>